### ISSUE TITLE
Test code for score_ramp function

### ISSUE THREAD

**Issue by jk-brown** [jk-brown/matilda#13]
Here's what I have for testing so far. I broke it up into 3 parts; testing errors, edge cases, and computation. 

dfs for testing:
```r
# testing df
r <- data.frame(x = rep(1,3), y = 1:3)

# df with nas
na <- data.frame(x = rep(NA, 3), y = 1:3)
```
Error tests:
```r 
test_that("function stops and produces error messgages", {

  # error when x and y not equal length
  expect_error(score_ramp(1:5, 1:6, w1 = 1, w2 = 2))

  # error when w1 not >= 0
  expect_error(score_ramp(1:5, 1:5, w1 = -1, w2 = 1))

  # error when w2 not >= w1
  expect_error(score_ramp(1:5, 1:5, w1 = 1, w2 = 0))

  # error when NAs in data
  expect_error(score_ramp(x = na$x, y = na$y, w1 = 0, w2 = 2))

})
```
**Error was automatically produced when NAs were present when I just ran the function with NA data in the console. So I left it as it is for now.**

Edge cases (using above df):
```r
test_that("scores assessed correctly based on w1 and w2 values", {

  # when w1 = 0 -- only diffs = 0 will score = 1; all other diffs (> 0) will score = 0
  expect_equal(score_ramp(x = r$x, y = r$y, w1 = 0, w2 = 1), c(1, 0, 0))

  # when w1 & w2 both equal the same value, diffs <= that value, score = 1; diffs > than that value will score = 0
  expect_equal(score_ramp(x = r$x, y = r$y, w1 = 1, w2 = 1), c(1, 1, 0))

  # when x-y diff is between w1 & w2 expect value between 0-1
  expect_gt(score_ramp(x = 2, y = 1, w1 = 0, w2 = 2), 0)
  expect_lt(score_ramp(x = 2, y = 1, w1 = 0, w2 = 2), 1)

  })
```
Last, I have a test for computing the scores in the cases where the differences are between w1 and w2
```r
test_that("x-y differences between w1 & w2 are computed accurately", {

# when x-y diff is between w1 & w2 expect computed score to equal
# 1 - (abs_diff - w1) / (w2-w1)
expect_equal(score_ramp(x = 2, y = 1, w1 = 0, w2 = 2), 1 - (abs(2 - 1) - 0) / (2 - 0))

})
```

**Comment by bpbond** [comment]
```
na <- data.frame(x = rep(NA, 3), y = 1:3)
```
This is one case: all values are NA. Another though might be a single one, e.g. `x = c(1, NA, 3)`. What should the function do in this case?

**Comment by jk-brown** [comment]
Thanks!

I added warnings for when some values of x or y are NAs. 

We can look at this a little more next week because it will be easier to discuss in person. But, this is the auto-error when all values are NA:

`NAs are not allowed in subscripted assignments`

And I am wondering if I should have a specific test for errors that R automatically produces like that?
