### ISSUE TITLE
How to make sure iterate_hector saves the output we want

### ISSUE THREAD

**Issue by bpbond** [jk-brown/matilda#33]
@jk-brown 

I was going through your vignette -- it is looking GREAT -- but paused when I got here:

>In order to screen our Hector runs based on observed CO~2~, we will need the `CO2_concentration` variable included in our Hector output. Therefore, we will include it as a desired variable when defining the metric.

>```{r}
># Setting a new_metric object for Hector analysis
>my_metric <- new_metric(c(GLOBAL_TAS(), CONCENTRATIONS_CO2()), 1960:2100, mean)

That is _super_ confusing. I mean, I understand what you're doing here, and why...but feel like the need to do this reflects a design flaw we should rethink.

**Comment by jk-brown** [comment]
I agree, I was also worried that was going to be a confusing way to achieve that step. I thought about this a bit more today and considered the following edit to `iterate_hector`:
```r
iterate_hector <- function(core, metric, crit, params) {

  # store results
  result_list <- list()

  # set number of model iterations
  for(i in seq_len(nrow(params))) {

    # convert params to numeric
    params_i <- unlist(params [i, ])

    # set variable values -- needs core and numeric param values
    set_params(core, params_i)

    # resets model after each run
    reset(core, date = 0)

    # run the model
    run(core)

    # fetch model results based on function arguments provided by the user
    metric_dat <- fetchvars(core = core, dates = metric$years, vars = metric$var)

    # adding run_number column to metric_dat
    metric_dat$run_number <- i

    ## New ##
    # fetch model results consistent with crit information
    crit_dat <- fetchvars(core = core, dates = crit$years, vars = crit$var)

    # adding run_number column to crit_dat
    crit_dat$run_number <- i

    # appending results filtered from crit and metic information
    dat <- rbind(crit_dat, metric_dat)

    # stores results
    result_list[[i]] <- dat

  }

  # concatenate list entries into a data frame and return
  do.call("rbind", result_list)
}
```

Not sure if this is the most straightforward way. But all it requires is the user to supply their scoring criterion in `iterate_hector`.

**Comment by jk-brown** [comment]
I'm finding that this solution does not work that well and gets confusing pretty quickly. 

this goes back to something you mentioned in out meeting on Tuesday - would it be worth creating a new "metric-like" object specifically for `iterate_hector` ?  so that the code would look like this:

```r
data <- save.data(variables, years)

iterate_hector(core, params, data)
```
Maybe this part is less important for right now but --- the only thing I can't figure out is how to let the user identify different year ranges for different variables. So if they want `global_tas` for 2000:2100 and `co2_concentration` for 1959:2100.
