### ISSUE TITLE
Example of user defining own scoring criterion

### ISSUE THREAD

**Issue by jk-brown** [jk-brown/matilda#38]
Currently, the vignette has the following as a code chunk to show an example of how to define your own criterion:
```r
# Create a new criteria that can be used to screen Hector runs
my_criterion<- new_criterion(CONCENTRATIONS_CO2(), 
                    years = metricdata_co2$year, 
                    obs_values = metricdata_co2$co2_ppm)

my_criterion
```
That chunk won't run because I have the `metricdata_co2` saved as internal data so it can't be accessed for examples etc.
Would it be better to 
1) don't run that code chunk 
2) make metricdata_co2 available so it can be used in the vignette example? 
3) just change this portion of the vignette to say something like "it is possible for the user to define their own criterion if observed data are obtained." and link to the `new_criterion` documentation?
4) Assign the internal data to an object and use it for the vignette example:
```r
metricdata_co2 <- matilda:::metricdata_co2

my_criterion<- new_criterion(CONCENTRATIONS_CO2(), 
                    years = metricdata_co2$year, 
                    obs_values = metricdata_co2$co2_ppm)

my_criterion
```

**Comment by bpbond** [comment]
I'd vote to do something simpler!

```r
my_criterion<- new_criterion(CONCENTRATIONS_CO2(), 
                    years = 1951:2000, 
                    obs_values = 301:350) # made-up time series
```

Or, given that our existing example already uses CO2, maybe something like

```r
my_criterion<- new_criterion(GLOBAL_TAS(), 
                    years = 1951:2000, 
                    obs_values = seq(0.4, 1.0, length.out = 50) # made-up time series
```
