### ISSUE TITLE
Using set.seed()

### ISSUE THREAD

**Issue by bpbond** [jk-brown/matilda#43]
Remind me please — let's discuss tomorrow @jk-brown

**Comment by jk-brown** [comment]
Will do. I have used `set.seed()` before. Are you thinking about this to the code chunks in the vignette?

**Comment by bpbond** [comment]
Basically, I just got a Hector error while building the vignette—I guess some random combination of parameters crashed the model (?). Anyway, that got me thinking:
* We should double-check that the package is using `try` around Hector calls
* The vignette should call `set.seed` before generating its parameter values, so we always know what's going to happen
