### ISSUE TITLE
Editing error assertions and test code for score_ramp and score_hruns

### ISSUE THREAD

**Issue by jk-brown** [jk-brown/matilda#57]
- [x] Edit test code for `score_ramp` - check error assertions in primary function -- 

> Secondary note for task above - go back and use a matrix with one row. Might be simplest testing formality.  

- [x] Edit test code in `score_hruns` - check error assertions in primary function

Question to remember for Ben -- This is a headache but I am wondering if using matrices in the score functions will actually work? The problem is that if `na.omit = T` the matrix will have differing dimensions and will cause an error. May need to search around for an alternative...not sure.

**Comment by bpbond** [comment]
Hmm. Right, if you apply `na.omit` then any rows with an NA in them will be dropped, but that affects the entire data frame or matrix... could you provide a short example of the problem?

**Comment by jk-brown** [comment]
Sorry for the long comment, thinking outloud for the second half  of the comment

```r
> m
     [,1] [,2] [,3] [,4]
[1,]    1    2    3   NA
[2,]    2   NA    4    5
[3,]    3    4   NA    6

score_ramp(m, w1 = 1, w2 = 2, na.omit = T)
[1] 0.6666667 0.3333333 0.0000000

Warning messages:
1: In obs_data - model_data :
  longer object length is not a multiple of shorter object length
2: In obs_data - model_data :
  longer object length is not a multiple of shorter object length
3: In obs_data - model_data :
  longer object length is not a multiple of shorter object length
```

So NAs will be omitted initially in cols = 2:4 (which represents the model data), leaving vectors of different lengths being passed to `abs(obs_data - model_data)` portion of the function. R recycles values to make the vector lengths equal, which gives an inaccurate result.

---
I guess just brainstorming I can put in a check for equal lengths and interrupt the function. This would make the user have to deal with NAs in the model data:

```r
  # Check the number of elements in obs_data and model_data matrices
    if (length(obs_data) != length(model_data))
      stop("Number of elements in obs_data and model_data matrices are not equal")
```

we had something similar to this the original score_ramp function, where we required the vector lengths be equal:

```r
if (length(x) != length(y)) stop("Length of x must be equal to length of y")
```

**Comment by bpbond** [comment]
That makes sense to me.
